# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 
---    
# Facts configuration.
- include: facts.yml
- include: interface-facts.yml
    
- block:
  - name: set PostgreSQL environment variables
    template:
      src: postgres.sh.j2
      dest: /var/lib/edb/.ppas_profile
      mode: 0644
    become_user: "{{ postgresql_user }}"

  - name: apply postgresql customizations
    blockinfile:
      name: "/etc/systemd/system/edb-as-{{ postgresql_major_version }}.{{ postgresql_minor_version }}.service"
      mode: 0644
      create: yes
      block: |
        .include /lib/systemd/system/edb-as-{{ postgresql_major_version }}.{{ postgresql_minor_version }}.service
        [Service]
        Environment=PGDATA={{ postgresql_data_dir }}

  - name: check if PostgreSQL database is initialized
    stat:
      path: "{{ postgresql_data_dir }}/PG_VERSION"
    register: pgdata_dir_version

  - name: initialize {{ postgresql_data_dir }}
    command: "{{ postgresql_bin_path }}/edb-as-{{ postgresql_major_version }}{{ postgresql_minor_version }}-setup initdb"
    when: not pgdata_dir_version.stat.exists
  
  - name: distributing CA certificates to all cluster nodes
    copy:
      src:  "{{ key_path }}/{{ item }}"
      dest: "{{ postgresql_data_dir }}"
      owner: "{{ postgresql_user }}"
      group: "{{ postgresql_user }}"
      mode: 0600
    with_items:
      - ca-cert.pem
      - ca-key.pem

  - name: check if certs are present
    stat:
      path: "{{ postgresql_data_dir}}/ca-key.key"
    register: pgdata_server_key

  - name: turn on SSL
    lineinfile:
      dest: "{{ postgresql_config_path }}/postgresql.conf"
      regexp: "^#ssl = off"
      backrefs: yes
      line: "ssl = on\t\t\t\t# (change requires restart)"

  - name: configuring postgresql SSL cert file
    lineinfile:
      dest: "{{ postgresql_config_path }}/postgresql.conf"
      regexp: "^#ssl_cert_file ="
      backrefs: yes
      line: "ssl_cert_file = 'ca-cert.pem'\t\t# (change requires restart)"
    become: true

  - name: configuring postgresql SSL key file
    lineinfile:
      dest: "{{ postgresql_config_path }}/postgresql.conf"
      regexp: "^#ssl_key_file ="
      backrefs: yes
      line: "ssl_key_file = 'ca-key.pem'\t\t# (change requires restart)"
    become: true

  - name: configure CA root certificate
    lineinfile:
      dest: "{{ postgresql_config_path }}/postgresql.conf"
      regexp: "^#ssl_ca_file ="
      backrefs: yes
      line: "ssl_ca_file = 'ca-cert.pem'\t\t# (change requires restart)"
    become: true
    notify: restart postgresql

    
  - name: listen on {{ postgresql_interface_ipv4 }}
    lineinfile:
      dest: "{{ postgresql_config_path }}/postgresql.conf"
      regexp: "^#?listen_addresses"
      backrefs: yes
      line: "listen_addresses = '{{ item }}'\t# what IP address(es) to listen on;"
    with_items: "{{ postgresql_interface_ipv4 }}"
    notify: restart postgresql        

  - name: set
    lineinfile:
      dest: "{{ postgresql_config_path }}/pg_hba.conf"
      regexp: "^host    all             all             127.0.0.1/32            ident"
      backrefs: yes
      line: "hostssl all             all             {{ postgresql_broadcast_interface_ipv4 }}/24            cert clientcert=1"
    notify: restart postgresql

  - name: Set trusted listener on data network
    lineinfile:
      dest: "{{ postgresql_config_path }}/pg_hba.conf"
      regexp: "^host    all             all             127.0.0.1/32            ident"
      backrefs: yes
      line: "hostssl all             all             {{ postgresql_broadcast_interface_ipv4 }}/24            cert clientcert=1"
    notify: restart postgresql
      
  - name: Configure global settings.
    lineinfile:
      dest: "{{ postgresql_config_path }}/postgresql.conf"
      regexp: "^#?{{ item.option }}.+$"
      line: "{{ item.option }} = '{{ item.value }}'"
      state: "{{ item.state | default('present') }}"
    with_items: "{{ postgresql_global_config_options }}"
    notify: restart postgresql
  
  - name: ensure PostgreSQL unix socket dirs exist
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ postgresql_user }}"
      group: "{{ postgresql_group }}"
      mode: 02775
    with_items: "{{ postgresql_unix_socket_directories }}"

  - name: update SE Linux enforcing mode
    sefcontext:
      target: "{{ postgresql_data_dir }}(/.*)?"
      setype: postgresql_db_t
      state: present
      reload: true
    when: ansible_selinux.status == "enabled"
      
  # sefcontent does not restore the context, so we need another step       
  - name: Restore SE Linux security context
    command: /sbin/restorecon -R {{ postgresql_data_dir }}
    when: ansible_selinux.status == "enabled"
  
  - name: Ensure PostgreSQL is started and enabled on boot
    systemd: "name={{ postgresql_daemon }} state=started enabled=True"
  
  # Configure PostgreSQL.
  - name: ensuring initial PostgreSQL databases are present
    postgresql_db:
      name: "{{ item.name }}"
      lc_collate: "{{ item.lc_collate | default('en_US.UTF-8') }}"
      lc_ctype: "{{ item.lc_ctype | default('en_US.UTF-8') }}"
      encoding: "{{ item.encoding | default('UTF-8') }}"
      template: "{{ item.template | default('template0') }}"
      login_host: "{{ item.login_host | default('localhost') }}"
      login_password: "{{ item.login_password | default(omit) }}"
      login_user: "{{ item.login_user | default(postgresql_user) }}"
      login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
      port: "{{ item.port | default('5444') }}"
      state: "{{ item.state | default('present') }}"
    with_items: "{{ postgresql_databases }}"
    become_user: "{{ postgresql_user }}"

  - name: ensuring initial PostgreSQL users are present
    postgresql_user:
      name: "{{ item.name }}"
      password: "{{ item.password | default(omit) }}"
      priv: "{{ item.priv | default(omit) }}"
      role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
      db: "{{ item.db | default(omit) }}"
      login_host: "{{ item.login_host | default('localhost') }}"
      login_password: "{{ item.login_password | default(omit) }}"
      login_user: "{{ item.login_user | default(postgresql_user) }}"
      login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
      port: "{{ item.port | default('5444') }}"
      state: "{{ item.state | default('present') }}"
    with_items: "{{ postgresql_users  }}"
    no_log: true
    become_user: "{{ postgresql_user }}"
  become: true
