# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 
#
# configure EDB yum repo
---
- block:
  - include_role:
      name: install-packages
    vars:
      package_list: ['http://yum.enterprisedb.com/edbrepos/edb-repo-{{ edb_yum }}.noarch.rpm'] 

  - blockinfile:
      path: /etc/yum.repos.d/edb.repo
      state: absent
      block: |
        [edbas{{ postgresql_major_version }}{{ postgresql_minor_version }}]
        name=EnterpriseDB Advanced Server {{ postgresql_major_version }}.{{ postgresql_minor_version }} $releasever - $basearch
        baseurl=http://<username>:<password>@yum.enterprisedb.com/{{ postgresql_major_version }}.{{ postgresql_minor_version }}/redhat/rhel-$releasever-$basearch
        enabled=0
        gpgcheck=1
        gpgkey=file:///etc/pki/rpm-gpg/ENTERPRISEDB-GPG-KEY
 
  - blockinfile:
      path: /etc/yum.repos.d/edb.repo
      state: absent
      block: |
        [enterprisedb-dependencies]
        name=EnterpriseDB Dependencies $releasever - $basearch
        baseurl=http://<username>:<password>@yum.enterprisedb.com/dependencies/redhat/rhel-$releasever-$basearch
        enabled=0
        gpgcheck=1
        gpgkey=file:///etc/pki/rpm-gpg/ENTERPRISEDB-GPG-KEY
  
  - name: enabling desired repository
    blockinfile:
      path: /etc/yum.repos.d/edb.repo
      block: |
        [edbas{{ postgresql_major_version }}{{ postgresql_minor_version }}]
        name=EnterpriseDB Advanced Server {{ postgresql_major_version }}.{{ postgresql_minor_version }} $releasever - $basearch
        baseurl=http://{{ edb_user }}:{{ edb_password }}@yum.enterprisedb.com/{{ postgresql_major_version }}.{{ postgresql_minor_version }}/redhat/rhel-$releasever-$basearch
        enabled=1
        gpgcheck=1
        gpgkey=file:///etc/pki/rpm-gpg/ENTERPRISEDB-GPG-KEY
        
        [enterprisedb-dependencies]
        name=EnterpriseDB Dependencies $releasever - $basearch
        baseurl=http://{{ edb_user }}:{{ edb_password }}@yum.enterprisedb.com/dependencies/redhat/rhel-$releasever-$basearch
        enabled=1
        gpgcheck=1
        gpgkey=file:///etc/pki/rpm-gpg/ENTERPRISEDB-GPG-KEY

  become: true
  